name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: Soynandin
          outputs: dist/snake.svg

      - name: Push Snake Animation to GitHub
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAGES_TOKEN }}
          publish_dir: ./dist
