name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Roda diariamente às 00:00 (UTC)
  workflow_dispatch:  # Permite execução manual

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Debugging Info
        run: echo "GitHub User:Soynandin"

      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: Soynandin
          outputs: dist/snake.svg

      - name: List files in dist
        run: ls -al ./dist

      - name: Verify Snake Animation Exists
        run: |
          if [ ! -f ./dist/snake.svg ]; then
            echo "Error: snake.svg not found!" && exit 1
          fi

      - name: Push Snake Animation to GitHub
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAGES_TOKEN }}
          publish_dir: ./dist

